name: CI/CD Demo

on:
  push:
    branches: [master, develop]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: checkout code
        uses: actions/checkout@v2

      - name: run lint
        run: yarn run lint

      - name: run test
        run: yarn run test
